/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	kubefloworgv1 "simjob/api/kubeflow.org/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSimJobs implements SimJobInterface
type FakeSimJobs struct {
	Fake *FakeKubeflowV1
	ns   string
}

var simjobsResource = schema.GroupVersionResource{Group: "kubeflow.org", Version: "v1", Resource: "simjobs"}

var simjobsKind = schema.GroupVersionKind{Group: "kubeflow.org", Version: "v1", Kind: "SimJob"}

// Get takes name of the simJob, and returns the corresponding simJob object, and an error if there is any.
func (c *FakeSimJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *kubefloworgv1.SimJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(simjobsResource, c.ns, name), &kubefloworgv1.SimJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubefloworgv1.SimJob), err
}

// List takes label and field selectors, and returns the list of SimJobs that match those selectors.
func (c *FakeSimJobs) List(ctx context.Context, opts v1.ListOptions) (result *kubefloworgv1.SimJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(simjobsResource, simjobsKind, c.ns, opts), &kubefloworgv1.SimJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubefloworgv1.SimJobList{ListMeta: obj.(*kubefloworgv1.SimJobList).ListMeta}
	for _, item := range obj.(*kubefloworgv1.SimJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested simJobs.
func (c *FakeSimJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(simjobsResource, c.ns, opts))

}

// Create takes the representation of a simJob and creates it.  Returns the server's representation of the simJob, and an error, if there is any.
func (c *FakeSimJobs) Create(ctx context.Context, simJob *kubefloworgv1.SimJob, opts v1.CreateOptions) (result *kubefloworgv1.SimJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(simjobsResource, c.ns, simJob), &kubefloworgv1.SimJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubefloworgv1.SimJob), err
}

// Update takes the representation of a simJob and updates it. Returns the server's representation of the simJob, and an error, if there is any.
func (c *FakeSimJobs) Update(ctx context.Context, simJob *kubefloworgv1.SimJob, opts v1.UpdateOptions) (result *kubefloworgv1.SimJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(simjobsResource, c.ns, simJob), &kubefloworgv1.SimJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubefloworgv1.SimJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSimJobs) UpdateStatus(ctx context.Context, simJob *kubefloworgv1.SimJob, opts v1.UpdateOptions) (*kubefloworgv1.SimJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(simjobsResource, "status", c.ns, simJob), &kubefloworgv1.SimJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubefloworgv1.SimJob), err
}

// Delete takes name of the simJob and deletes it. Returns an error if one occurs.
func (c *FakeSimJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(simjobsResource, c.ns, name), &kubefloworgv1.SimJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSimJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(simjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &kubefloworgv1.SimJobList{})
	return err
}

// Patch applies the patch and returns the patched simJob.
func (c *FakeSimJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubefloworgv1.SimJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(simjobsResource, c.ns, name, pt, data, subresources...), &kubefloworgv1.SimJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubefloworgv1.SimJob), err
}
